### ISSUE TITLE
no items shown in trader menu

### ISSUE THREAD

**Issue by Masadda** [DevZupa/AdvancedTrading#12]
Dont know if this is the rigth place to ask:

i've installed adv. trade 2.1 together with zsc 3.0, and there are no items shown in the adv. trader menues. the menu itself is displayed properly, but neither what the trader sells, nor what i can sell.
edit: is the "Z_AT_DIALOGWINDOW" an actual file? if yes, it is missing in the zip for version 2.1

**Comment by ghost** [comment]
it blocked by infistar.de AntiHack, i have same problem
